# Generated by Django 2.2.6 on 2020-05-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200525_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewMember',
            new_name='Member',
        ),
    ]
