# Generated by Django 2.2.6 on 2020-05-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200526_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
